### ISSUE TITLE
Mainly kudos

### ISSUE THREAD

**Issue by aaraney** [mandli/tsunami-models#2]
Thanks to my feed I saw this. Im excited to see where this goes, as a layperson in the realms of this topic I am more excited to learn than anything. Have you all considered using [`pandoc-scholar`](https://github.com/pandoc-scholar/pandoc-scholar) for the projects collaborative writing? I started using it recently and have really enjoyed the simplicity and flexibility. 

Anyway, this can probably be closed... kudos :clap: :clap: :clap:

**Comment by mandli** [comment]
Thanks @aaraney!  The only collaborative paper we have written so far was the one in https://github.com/clawpack/doc/tree/dev/papers/clawpack-5x, which had to conform to PeerJ's formatting.  We also were somewhat wedded to using Overleaf as we are all a bunch of LaTeX users.  Definitely will keep pandoc-scholar in mind though.  I recently figured out how to get pandoc to produce an [html bibliography](https://gist.github.com/mandli/7e202f4b568ac69b01ff4386066b8a4b), which I was excited about.

**Comment by aaraney** [comment]
For sure @mandli! That totally makes sense, I know you to like overleaf. I thought pandoc-scholar was a nice syntactical compromise without really compromising features, but certainly doesnt have the luxury features of a service like overleaf. 

Nice! Thanks for the share. It would be nice to have something like that as a zotero plugin.
