### ISSUE TITLE
Add package to your list

### ISSUE THREAD

**Issue by stoiver** [mandli/tsunami-models#3]
@mandli nice job of collecting a wide range of tsunami software packages. I am hoping you would consider adding ANUGA https://github.com/anuga-community/anuga_core

I would be happy to create a PR with the ANUGA details.

**Comment by mandli** [comment]
Would love to add ANUGA!  Please create a PR to add it when you get a chance.

**Comment by smarras79** [comment]
hi @stoiver I added ANUGA. thanks for the suggestion.
All the best.
